[project]
name = "urssi_pixi-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["squang <squang@vols.utk.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
